Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,8 +10,29 @@ jobs:
   steps:
   - task: UsePythonVersion@0
     inputs:
-      versionSpec: '3.x'
-    displayName: 'Install Python'
+     script: |
+        set -e  # Exit immediately if any command returns a non-zero status
+        
+        # Check if Python is already installed
+        if ! command -v python3 >/dev/null 2>&1 ; then
+          # Install Python binaries from prebuilt package without using sudo
+          curl -O https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz
+          tar -xf Python-3.9.9.tgz
+          cd Python-3.9.9
+          ./configure --prefix=$HOME/python
+          make -j 4
+          make install
+          cd ..
+          rm -rf Python-3.9.9 Python-3.9.9.tgz
+          export PATH=$HOME/python/bin:$PATH
+        else
+          echo "Python is already installed."
+        fi
+
+  - task: UsePythonVersion@0
+    inputs:
+      versionSpec: '3.9.x'
+    displayName: 'Set Python version'
 
 - job: CallingGetApi
   displayName: 'Calling Get API and Displaying the response'
